export type IncidentType = 'espionage' | 'destructive' | 'ransomware' | 'financial' | 'influence' | 'supply-chain' | 'breach';
export type ImpactLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM';

export interface CyberIncident {
  id: string;
  name: string;
  date: string;       // YYYY-MM or YYYY-MM-DD
  year: number;
  nation: string;     // attributed nation, or 'Criminal' / 'Unknown'
  actors: string[];
  targets: string[];
  type: IncidentType;
  impact: ImpactLevel;
  summary: string;
  details: string;
  damage?: string;
  tags: string[];
}

export const INCIDENTS: CyberIncident[] = [
  {
    id: 'stuxnet',
    name: 'Stuxnet',
    date: '2010-06',
    year: 2010,
    nation: 'USA / Israel',
    actors: ['NSA', 'Unit 8200'],
    targets: ['Iran Natanz Nuclear Facility', 'Siemens PLCs'],
    type: 'destructive',
    impact: 'CRITICAL',
    summary: 'First known nation-state cyberweapon designed to physically destroy industrial equipment, targeting Iranian uranium centrifuges.',
    details: 'Stuxnet exploited four Windows zero-days simultaneously — unprecedented at the time. The worm spread via USB drives and specifically sought Siemens S7-315 PLCs connected to specific frequency converters. It manipulated centrifuge speeds to cause physical damage while reporting normal operation to operators. Estimated to have destroyed roughly 1,000 centrifuges and set back Iran\'s nuclear program by 1-2 years.',
    tags: ['zero-day', 'ICS/SCADA', 'nuclear', 'PLC', 'USB propagation'],
  },
  {
    id: 'operation-aurora',
    name: 'Operation Aurora',
    date: '2009-12',
    year: 2009,
    nation: 'China',
    actors: ['APT17', 'Elderwood Group'],
    targets: ['Google', 'Adobe', 'Intel', 'Morgan Stanley', '30+ tech firms'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Coordinated espionage campaign against major US tech companies, stealing source code and targeting Gmail accounts of Chinese dissidents.',
    details: 'Attackers exploited a zero-day in Internet Explorer to gain access to Google\'s corporate infrastructure. Google discovered the attackers accessed the Gmail accounts of Chinese human rights activists and the source code repository for many Google products. The disclosure led Google to threaten to exit China, which it ultimately did in search operations. Analysts attributed the operation to the Chinese military.',
    tags: ['zero-day', 'source code theft', 'IE exploit', 'Google'],
  },
  {
    id: 'rsa-secureid-breach',
    name: 'RSA SecurID Breach',
    date: '2011-03',
    year: 2011,
    nation: 'China',
    actors: ['APT1', 'Comment Crew'],
    targets: ['RSA Security', 'US Defense Contractors'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Theft of RSA\'s SecurID seed records enabled follow-on attacks against Lockheed Martin, Northrop Grumman, and L-3 Communications.',
    details: 'Attackers sent a phishing email with an embedded Flash zero-day to RSA employees. The breach extracted seed records for tens of millions of SecurID tokens — the core authentication secret. Months later, attackers used forged tokens to breach Lockheed Martin\'s network. RSA spent $66M on remediation and replaced tokens for government and defense clients.',
    damage: '$66M+ remediation',
    tags: ['phishing', 'supply chain', 'two-factor auth', 'defense contractors'],
  },
  {
    id: 'shamoon',
    name: 'Shamoon / Disttrack',
    date: '2012-08',
    year: 2012,
    nation: 'Iran',
    actors: ['APT33', 'Cutting Sword of Justice'],
    targets: ['Saudi Aramco', 'RasGas'],
    type: 'destructive',
    impact: 'CRITICAL',
    summary: 'Disk-wiping malware destroyed 35,000 workstations at Saudi Aramco — the world\'s most valuable company — rendering them inoperable.',
    details: 'Shamoon overwrote the master boot record and replaced files with an image of a burning US flag. Saudi Aramco was forced to disconnect from the internet for over a week and resorted to buying hard drives from neighboring countries. The attack is considered one of the most destructive cyberattacks in history. A follow-on Shamoon 2 campaign targeted Saudi government agencies in 2016.',
    tags: ['wiper', 'energy sector', 'MBR', 'Gulf', 'Shamoon 2'],
  },
  {
    id: 'target-breach',
    name: 'Target Retail Breach',
    date: '2013-11',
    year: 2013,
    nation: 'Criminal',
    actors: ['Rescator', 'Eastern European cybercriminals'],
    targets: ['Target Corporation', '110M customers'],
    type: 'breach',
    impact: 'HIGH',
    summary: 'POS malware stolen via third-party HVAC vendor credentials compromised 40M credit cards and 70M customer records.',
    details: 'Attackers infiltrated Target\'s network through credentials stolen from an HVAC subcontractor. They installed BlackPOS malware on point-of-sale systems across 1,797 stores. The breach ran undetected for three weeks during the holiday shopping season. Target\'s security monitoring tools flagged the activity but alerts were not escalated. CEO and CIO resigned following congressional hearings.',
    damage: '$202M total losses',
    tags: ['POS malware', 'supply chain', 'retail', 'credit cards', 'third-party access'],
  },
  {
    id: 'sony-pictures-hack',
    name: 'Sony Pictures Hack',
    date: '2014-11',
    year: 2014,
    nation: 'North Korea',
    actors: ['Lazarus Group', 'GOP (Guardians of Peace)'],
    targets: ['Sony Pictures Entertainment'],
    type: 'destructive',
    impact: 'CRITICAL',
    summary: 'Destructive wiper attack combined with massive data leak in retaliation for the film "The Interview" — forced Sony to withdraw the movie.',
    details: 'Lazarus Group deployed the WhiskeyBravo wiper alongside a massive exfiltration of 100TB of data including unreleased films, executive emails, employee Social Security numbers, and salary data. The hackers threatened theaters showing "The Interview," causing Sony to briefly cancel the release. The Obama administration publicly attributed the attack to North Korea — a rare formal attribution — and imposed sanctions.',
    damage: '$100M+ estimated',
    tags: ['wiper', 'film industry', 'retaliation', 'data leak', 'attribution'],
  },
  {
    id: 'opm-hack',
    name: 'OPM Hack',
    date: '2015-04',
    year: 2015,
    nation: 'China',
    actors: ['APT41', 'Deep Panda'],
    targets: ['Office of Personnel Management', 'US federal employees'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Theft of 21.5M security clearance background investigation files — the most significant US government data breach ever recorded.',
    details: 'Attackers accessed OPM networks for over a year. They stole Standard Form 86 records containing deeply personal information: foreign contacts, mental health history, drug use, financial data, and fingerprints for 5.6M cleared individuals. The SF-86 data is considered a goldmine for foreign intelligence services to recruit, blackmail, or identify undercover officers. DIA later attributed foreign contacts being burned to this breach.',
    tags: ['espionage', 'clearances', 'SF-86', 'counterintelligence', 'fingerprints'],
  },
  {
    id: 'ukraine-power-grid-2015',
    name: 'Ukraine Power Grid Attack',
    date: '2015-12',
    year: 2015,
    nation: 'Russia',
    actors: ['Sandworm', 'APT28'],
    targets: ['Prykarpattya Oblenergo', 'Ukrainian power distribution'],
    type: 'destructive',
    impact: 'HIGH',
    summary: 'First confirmed cyberattack to cause power outages — 230,000 Ukrainians lost electricity for up to 6 hours.',
    details: 'Sandworm used spearphishing to deliver BlackEnergy malware months before the attack. On December 23, attackers simultaneously opened breakers at multiple substations, launched a telephone denial-of-service against the utility\'s call center to slow response, and deployed KillDisk to wipe operator workstations. A follow-on attack in December 2016 used Industroyer/Crash Override malware targeting the Kiev transmission grid.',
    tags: ['ICS/SCADA', 'power grid', 'BlackEnergy', 'KillDisk', 'critical infrastructure'],
  },
  {
    id: 'bangladesh-bank-heist',
    name: 'Bangladesh Bank SWIFT Heist',
    date: '2016-02',
    year: 2016,
    nation: 'North Korea',
    actors: ['Lazarus Group', 'APT38'],
    targets: ['Bangladesh Bank', 'Federal Reserve Bank of New York'],
    type: 'financial',
    impact: 'CRITICAL',
    summary: 'North Korea attempted to steal $951M from Bangladesh\'s central bank via fraudulent SWIFT messages — $81M reached criminal accounts.',
    details: 'APT38 spent nearly a year inside Bangladesh Bank\'s network, studying SWIFT messaging patterns and operator behavior. They submitted 35 fraudulent transfer requests through the Fed\'s legitimate SWIFT terminal late on a Thursday. A $951M theft was prevented only by a typographical error ("fandation" instead of "foundation") that triggered a manual review. $81M reached accounts in the Philippines and was largely laundered through casinos.',
    damage: '$81M stolen',
    tags: ['SWIFT', 'financial theft', 'central bank', 'APT38', 'money laundering'],
  },
  {
    id: 'dnc-hack',
    name: 'DNC Hack / Operation Grizzly Steppe',
    date: '2016-03',
    year: 2016,
    nation: 'Russia',
    actors: ['APT28 (Fancy Bear)', 'APT29 (Cozy Bear)'],
    targets: ['Democratic National Committee', 'John Podesta', 'DCCC'],
    type: 'influence',
    impact: 'CRITICAL',
    summary: 'Russian intelligence hacked the DNC and Clinton campaign, releasing documents via WikiLeaks to influence the 2016 US presidential election.',
    details: 'Both GRU (APT28) and SVR (APT29) independently penetrated DNC networks. APT29 entered first in 2015 via spearphishing. APT28 followed in March 2016. GRU officers (later indicted) created personas "Guccifer 2.0" and DCLeaks to distribute stolen documents. WikiLeaks coordinated release timing to maximize electoral impact. The Mueller investigation indicted 12 GRU officers by name for this operation.',
    tags: ['influence operation', 'election interference', 'GRU', 'SVR', 'WikiLeaks'],
  },
  {
    id: 'mirai-botnet',
    name: 'Mirai Botnet / Dyn DDoS',
    date: '2016-10',
    year: 2016,
    nation: 'Criminal',
    actors: ['Paras Jha', 'Josiah White', 'Dalton Norman'],
    targets: ['Dyn DNS', 'Twitter, Netflix, Reddit, Spotify'],
    type: 'destructive',
    impact: 'HIGH',
    summary: 'IoT botnet of 600,000+ devices took down major DNS infrastructure, making large swaths of the US internet unreachable for hours.',
    details: 'Three college students built Mirai to target Minecraft servers, then released the source code publicly. The October 21 Dyn attack reached 1.2 Tbps — the largest DDoS ever recorded at the time. Mirai compromised IoT devices (cameras, DVRs, routers) by scanning for default credentials. The public release of source code spawned dozens of Mirai variants still in use today.',
    tags: ['DDoS', 'IoT', 'botnet', 'DNS', 'default credentials'],
  },
  {
    id: 'wannacry',
    name: 'WannaCry Ransomware',
    date: '2017-05',
    year: 2017,
    nation: 'North Korea',
    actors: ['Lazarus Group'],
    targets: ['NHS UK', 'FedEx', 'Deutsche Bahn', '200,000+ organizations in 150 countries'],
    type: 'ransomware',
    impact: 'CRITICAL',
    summary: 'Self-propagating ransomware using stolen NSA EternalBlue exploit spread to 200,000+ systems in 150 countries within hours.',
    details: 'WannaCry used EternalBlue (MS17-010) — a stolen NSA exploit leaked by Shadow Brokers — to spread without user interaction across unpatched Windows systems. The UK NHS was hardest hit, canceling 19,000 appointments and ambulances. A "kill switch" domain registered by security researcher Marcus Hutchins halted propagation within 24 hours. Microsoft had released a patch (MS17-010) two months prior but millions of systems remained unpatched.',
    damage: '$4-8B estimated global damage',
    tags: ['EternalBlue', 'SMB', 'NHS', 'worm', 'NSA tools', 'kill switch'],
  },
  {
    id: 'notpetya',
    name: 'NotPetya',
    date: '2017-06',
    year: 2017,
    nation: 'Russia',
    actors: ['Sandworm', 'GRU Unit 74455'],
    targets: ['Maersk', 'Merck', 'FedEx/TNT', 'Mondelez', 'Ukraine critical infrastructure'],
    type: 'destructive',
    impact: 'CRITICAL',
    summary: 'Destructive cyberweapon disguised as ransomware caused $10B in global damage — the costliest cyberattack in history.',
    details: 'NotPetya was distributed via a trojanized update to M.E.Doc, Ukrainian accounting software used by 80% of businesses operating in Ukraine. Unlike ransomware, it had no functional payment mechanism — decryption was impossible. It spread globally via EternalBlue, credential harvesting (Mimikatz), and legitimate Windows admin tools. Maersk lost 45,000 PCs and 4,000 servers; they reinstalled an entire global IT infrastructure in 10 days. The US, UK, EU, and Australia formally attributed the attack to GRU.',
    damage: '$10B+ global',
    tags: ['wiper', 'EternalBlue', 'Mimikatz', 'supply chain', 'Ukraine', 'shipping'],
  },
  {
    id: 'triton-trisis',
    name: 'TRITON / TRISIS',
    date: '2017-08',
    year: 2017,
    nation: 'Russia',
    actors: ['TEMP.Veles', 'CISA TEMP.Veles', 'Sandworm-linked'],
    targets: ['Saudi Aramco Petro Rabigh', 'Schneider Electric Triconex SIS'],
    type: 'destructive',
    impact: 'CRITICAL',
    summary: 'First malware designed to attack safety instrumented systems — intended to disable safety systems and cause a catastrophic industrial explosion.',
    details: 'TRITON targeted Triconex Safety Instrumented System (SIS) controllers, which are the last line of defense against catastrophic industrial accidents. Attackers spent two years in the network before deploying TRITON. A programming error caused the SIS to trip into safe mode, alerting operators and preventing what would have been a catastrophic explosion. FireEye later linked the malware development to the Central Scientific Research Institute of Chemistry and Mechanics (TsNIIKhM), a Russian government research institute.',
    tags: ['ICS/SCADA', 'safety systems', 'energy', 'SIS', 'potential mass casualties'],
  },
  {
    id: 'equifax-breach',
    name: 'Equifax Data Breach',
    date: '2017-05',
    year: 2017,
    nation: 'China',
    actors: ['APT10', 'PLA 54th Research Institute'],
    targets: ['Equifax', '147M Americans'],
    type: 'breach',
    impact: 'CRITICAL',
    summary: 'Unpatched Apache Struts vulnerability exposed SSNs, birth dates, and credit data for 147M Americans. Four PLA officers indicted.',
    details: 'Attackers exploited CVE-2017-5638 in Apache Struts — a publicly known vulnerability with a patch available for two months. Equifax\'s security team failed to patch the system. Attackers ran 9,000 SQL queries over 76 days, exfiltrating data in 30 separate encrypted archives. Equifax\'s security monitoring certificate had expired 19 months prior, blinding their detection systems. DOJ indicted four members of the PLA\'s 54th Research Institute.',
    damage: '$1.38B total settlements',
    tags: ['Apache Struts', 'unpatched vulnerability', 'PII', 'PLA', 'credit bureau'],
  },
  {
    id: 'solarwinds-sunburst',
    name: 'SolarWinds / SUNBURST',
    date: '2020-10',
    year: 2020,
    nation: 'Russia',
    actors: ['APT29 (Cozy Bear)', 'SVR'],
    targets: ['SolarWinds', 'US Treasury', 'CISA', 'NSA', 'DOJ', '18,000+ organizations'],
    type: 'supply-chain',
    impact: 'CRITICAL',
    summary: 'SVR compromised SolarWinds build pipeline to distribute backdoored Orion updates to 18,000 customers including US government agencies.',
    details: 'APT29 accessed SolarWinds\' build environment and inserted SUNBURST malware into the Orion IT monitoring software update pipeline. The backdoor lay dormant for 14 days post-installation before activating, used domain generation algorithms and traffic blending to evade detection, and had a hard-coded kill switch for Kaspersky installations. Approximately 100 companies and 9 US government agencies were deeply compromised. Discovered by FireEye after noticing their own red team tools were stolen.',
    tags: ['supply chain', 'build pipeline', 'Orion', 'SVR', 'government', 'SUNBURST'],
  },
  {
    id: 'hafnium-exchange',
    name: 'HAFNIUM / Exchange ProxyLogon',
    date: '2021-01',
    year: 2021,
    nation: 'China',
    actors: ['HAFNIUM', 'APT41', 'Tick', 'LuckyMouse'],
    targets: ['Microsoft Exchange Servers', '250,000+ organizations globally'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Four Exchange zero-days exploited by Chinese actors, then mass-exploited by multiple APTs — compromising 250,000+ servers before patching.',
    details: 'HAFNIUM initially used four chained zero-days (ProxyLogon: CVE-2021-26855, 26857, 26858, 27065) to access on-premise Exchange servers and install web shells. Microsoft\'s patch release on March 2 triggered a feeding frenzy — at least 10 different threat actor groups began mass exploitation within hours. At peak, 30,000 US organizations were compromised in a single day. CISA issued emergency directive 21-02. Ransomware groups followed weeks later.',
    tags: ['zero-day', 'Exchange', 'ProxyLogon', 'web shell', 'email server'],
  },
  {
    id: 'colonial-pipeline',
    name: 'Colonial Pipeline Ransomware',
    date: '2021-05',
    year: 2021,
    nation: 'Criminal',
    actors: ['DarkSide'],
    targets: ['Colonial Pipeline'],
    type: 'ransomware',
    impact: 'CRITICAL',
    summary: 'Ransomware attack on the largest US fuel pipeline caused a week-long shutdown, triggering gas shortages across the US Southeast.',
    details: 'DarkSide gained access via a compromised VPN password (no MFA). Colonial preemptively shut down the pipeline — the OT network itself was not directly attacked. The shutdown of 5,500 miles of pipeline (45% of East Coast fuel supply) caused gas shortages in 12 states, panic buying, and a spike in fuel prices. Colonial paid $4.4M ransom within hours. DOJ recovered $2.3M of the payment by seizing the crypto wallet private key. Biden declared national emergency.',
    damage: '$4.4M ransom; $100M+ economic impact',
    tags: ['ransomware', 'energy', 'critical infrastructure', 'DarkSide', 'VPN', 'no-MFA'],
  },
  {
    id: 'revel-kaseya',
    name: 'Kaseya VSA / REvil',
    date: '2021-07',
    year: 2021,
    nation: 'Criminal',
    actors: ['REvil', 'Sodinokibi'],
    targets: ['Kaseya VSA', '1,500 downstream businesses', 'Managed Service Providers'],
    type: 'ransomware',
    impact: 'CRITICAL',
    summary: 'Supply chain ransomware attack via MSP software compromised 1,500 businesses simultaneously — REvil demanded $70M universal decryptor.',
    details: 'REvil exploited a zero-day in Kaseya VSA (remote monitoring software used by MSPs) to push ransomware to all managed endpoints simultaneously. The attack launched hours before the July 4th US holiday weekend. 1,500 businesses in 17 countries were encrypted, including Swedish grocery chain Coop (which closed 800 stores). REvil demanded $70M for a universal decryptor. Days after the attack, REvil\'s infrastructure went dark — believed to be US/RU law enforcement pressure.',
    damage: '$70M demanded; $100M+ in damages',
    tags: ['supply chain', 'MSP', 'REvil', 'zero-day', 'holiday weekend'],
  },
  {
    id: 'log4shell',
    name: 'Log4Shell (Log4j)',
    date: '2021-12',
    year: 2021,
    nation: 'Multiple',
    actors: ['APT41', 'APT10', 'Conti', 'Lazarus Group', 'multiple state and criminal actors'],
    targets: ['Virtually every Java-based application globally'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Remote code execution zero-day in the ubiquitous Log4j library — CISA called it the most serious vulnerability in a decade.',
    details: 'CVE-2021-44228 allowed unauthenticated remote code execution via a single malicious string in any logged field. Log4j is embedded in hundreds of thousands of products from Apple iCloud to Twitter to AWS services. CISA Director Jen Easterly called it "the most serious vulnerability I have seen in my decades-long career." Nation-state actors from China, Iran, North Korea, and Russia all began exploitation within 24 hours of disclosure. Belgian Defense Ministry was among the first government victims.',
    tags: ['RCE', 'zero-day', 'Java', 'ubiquitous library', 'supply chain'],
  },
  {
    id: 'conti-costa-rica',
    name: 'Conti vs. Costa Rica',
    date: '2022-04',
    year: 2022,
    nation: 'Criminal',
    actors: ['Conti'],
    targets: ['Costa Rica government', 'Ministry of Finance', 'CCSS'],
    type: 'ransomware',
    impact: 'HIGH',
    summary: 'Conti ransomware forced Costa Rica to declare a national emergency — first nation to do so due to a ransomware attack.',
    details: 'Conti attacked multiple Costa Rican government agencies simultaneously, crippling the Ministry of Finance\'s tax and customs system for weeks and disrupting $200M+ in daily trade. President Chaves declared a national emergency immediately upon taking office. Conti subsequently attacked Costa Rica\'s Social Security Fund (CCSS), taking down its HR systems. Conti threatened to overthrow the government. The group disbanded weeks later, believed to be rebranding due to post-Ukraine data leak.',
    damage: '$30M+ direct damages',
    tags: ['ransomware', 'government', 'national emergency', 'Conti', 'Central America'],
  },
  {
    id: 'uber-breach-2022',
    name: 'Uber Breach (Lapsus$)',
    date: '2022-09',
    year: 2022,
    nation: 'Criminal',
    actors: ['Lapsus$', 'Scattered Spider (related)'],
    targets: ['Uber Technologies'],
    type: 'breach',
    impact: 'HIGH',
    summary: 'Teen hackers used MFA fatigue attack to fully compromise Uber\'s internal systems, including VPN, Slack, AWS, and Google Workspace.',
    details: 'Attackers purchased employee credentials from a dark web broker, then bombarded the employee with MFA push notifications until they accepted. Once inside, they discovered a PowerShell script containing hardcoded admin credentials to Uber\'s PAM solution, giving total access. The attacker announced the breach in Uber\'s own Slack. An 18-year-old British national was later arrested. Uber\'s former CSO Joe Sullivan was also facing federal charges for covering up a 2016 breach.',
    tags: ['MFA fatigue', 'Lapsus$', 'social engineering', 'privileged access', 'teens'],
  },
  {
    id: 'lastpass-breach',
    name: 'LastPass Breach',
    date: '2022-08',
    year: 2022,
    nation: 'Criminal',
    actors: ['Unknown'],
    targets: ['LastPass', '33M users'],
    type: 'breach',
    impact: 'CRITICAL',
    summary: 'Attackers stole encrypted password vaults for 33M users plus decryption metadata — enabling offline brute-force of master passwords.',
    details: 'A two-stage attack first stole source code and technical information, then used that to target a DevOps engineer\'s home system to steal credentials to an AWS S3 bucket containing customer vault exports. The exported vaults contained URLs in plaintext and passwords encrypted with AES-256. LastPass\'s 2022 communications were widely criticized for downplaying the severity. Subsequent $35M crypto thefts were linked to cracked LastPass vaults.',
    tags: ['password manager', 'vault', 'crypto theft', 'supply chain', 'developer targeting'],
  },
  {
    id: 'moveit-clop',
    name: 'MOVEit Transfer / Cl0p',
    date: '2023-05',
    year: 2023,
    nation: 'Criminal',
    actors: ['Cl0p', 'TA505'],
    targets: ['2,600+ organizations', 'US federal agencies', 'Shell', 'BBC', 'BA', 'Zellis'],
    type: 'ransomware',
    impact: 'CRITICAL',
    summary: 'SQL injection zero-day in MOVEit file transfer software breached 2,600+ organizations, compromising 77M+ individuals — largest breach of 2023.',
    details: 'Cl0p mass-exploited CVE-2023-34362, a SQL injection vulnerability in MOVEit Transfer. The group had likely stockpiled the zero-day for months, deploying it simultaneously against hundreds of targets over Memorial Day weekend. Unlike typical ransomware, Cl0p focused exclusively on data exfiltration and extortion without encryption. US federal agencies including the Department of Energy and CDPH were hit. The hack ultimately affected 77M+ people.',
    damage: '$10B+ estimated economic impact',
    tags: ['zero-day', 'SQL injection', 'Cl0p', 'file transfer', 'mass exploitation'],
  },
  {
    id: 'mgm-scattered-spider',
    name: 'MGM / Caesars — Scattered Spider',
    date: '2023-09',
    year: 2023,
    nation: 'Criminal',
    actors: ['Scattered Spider', 'ALPHV/BlackCat'],
    targets: ['MGM Resorts International', 'Caesars Entertainment'],
    type: 'ransomware',
    impact: 'HIGH',
    summary: 'Social engineering attack crippled MGM\'s Las Vegas casino operations for 10 days; Caesars quietly paid $15M ransom.',
    details: 'Scattered Spider (suspected US/UK teenagers) found an MGM IT employee on LinkedIn, then called the help desk impersonating them to reset credentials. Within 10 minutes of help desk contact, they were inside. MGM refused to pay ransom and shut down critical systems, taking down hotel check-ins, slot machines, digital room keys, and ATMs across multiple properties for 10 days. Caesars paid approximately $15M of a $30M ransom demand. Five US citizens were indicted.',
    damage: '$100M+ for MGM; $15M ransom for Caesars',
    tags: ['social engineering', 'vishing', 'casino', 'Scattered Spider', 'helpdesk'],
  },
  {
    id: 'change-healthcare',
    name: 'Change Healthcare Ransomware',
    date: '2024-02',
    year: 2024,
    nation: 'Criminal',
    actors: ['ALPHV/BlackCat', 'RansomHub (follow-on)'],
    targets: ['Change Healthcare (UnitedHealth Group)', 'US healthcare system'],
    type: 'ransomware',
    impact: 'CRITICAL',
    summary: 'The largest healthcare cyberattack in US history disrupted prescription processing for 1 in 3 Americans for weeks. UHG paid $22M ransom.',
    details: 'Attackers gained access via a Citrix portal with no MFA. Change Healthcare processes 15B healthcare transactions annually — 40% of US health insurance claims. Pharmacies could not process prescriptions, hospitals couldn\'t verify coverage, providers couldn\'t get paid. UHG paid ALPHV $22M in ransom. ALPHV then exit-scammed its affiliate, who subsequently joined RansomHub and demanded additional payment — double extortion. Total records exposed: 100M Americans.',
    damage: '$22M ransom; $1.6B UHG losses Q1 2024; $100M in provider loans',
    tags: ['healthcare', 'ransomware', 'Citrix', 'no-MFA', 'double extortion', 'prescription systems'],
  },
  {
    id: 'midnight-blizzard-microsoft',
    name: 'Midnight Blizzard / Microsoft',
    date: '2024-01',
    year: 2024,
    nation: 'Russia',
    actors: ['APT29 (Midnight Blizzard / Cozy Bear)', 'SVR'],
    targets: ['Microsoft Corporate Email', 'US Government Agencies'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'SVR accessed Microsoft senior executive email accounts for months, reading correspondence about SVR itself and extracting authentication secrets.',
    details: 'APT29 used password spraying against a legacy non-production test tenant account with no MFA. From there, they pivoted to access email accounts of Microsoft\'s senior leadership, cybersecurity, and legal teams. Critically, they accessed communications about what Microsoft knew of the SVR\'s own operations. The attackers also found authentication secrets (OAuth tokens, API keys) shared via email that enabled access to some customer systems. HPE disclosed a related breach by the same group.',
    tags: ['SVR', 'password spray', 'legacy tenant', 'no-MFA', 'executive email', 'OAuth'],
  },
  {
    id: 'volt-typhoon',
    name: 'Volt Typhoon / KV-Botnet',
    date: '2024-01',
    year: 2024,
    nation: 'China',
    actors: ['Volt Typhoon', 'Bronze Silhouette'],
    targets: ['US critical infrastructure', 'power grid', 'water', 'communications', 'Guam military'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'PRC pre-positioned in US critical infrastructure for "at least 5 years" — CISA confirmed goal is disruption capability for conflict over Taiwan.',
    details: 'Volt Typhoon used living-off-the-land (LOTL) techniques — legitimate system tools like netsh, wmic, ntdsutil — to blend in with normal traffic. They built a covert relay network using compromised SOHO routers (Cisco, Netgear, ASUS) to proxy traffic, making attribution and blocking extremely difficult. CISA, FBI, NSA issued joint advisory warning the pre-positioning was not intelligence collection but preparation to "disrupt or destroy critical infrastructure" in event of US-China conflict.',
    tags: ['living-off-the-land', 'critical infrastructure', 'pre-positioning', 'Taiwan', 'SOHO routers', 'LOTL'],
  },
  {
    id: 'salt-typhoon-telecom',
    name: 'Salt Typhoon / Telecom Wiretap',
    date: '2024-09',
    year: 2024,
    nation: 'China',
    actors: ['Salt Typhoon', 'Earth Estries'],
    targets: ['AT&T', 'Verizon', 'T-Mobile', 'Lumen', 'US wiretap infrastructure'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'PRC compromised major US carriers\' lawful intercept systems — wiretapping US government officials and reading law enforcement surveillance targets for months.',
    details: 'Salt Typhoon accessed CALEA-mandated lawful interception infrastructure — systems designed for government wiretap orders — inside AT&T, Verizon, and Lumen. They read metadata and content for calls involving senior US government officials including Trump and Harris campaign members. Critically, they accessed lists of individuals under US law enforcement surveillance, potentially exposing US intelligence sources and methods. FBI Director Wray called it "the most significant cyber espionage campaign in history." No carrier has confirmed full eviction.',
    tags: ['CALEA', 'wiretap', 'telecom', 'espionage', 'government officials', 'FISA'],
  },
  {
    id: 'snowflake-breach',
    name: 'Snowflake Cloud Breach',
    date: '2024-04',
    year: 2024,
    nation: 'Criminal',
    actors: ['ShinyHunters', 'UNC5537'],
    targets: ['Ticketmaster', 'AT&T', 'Santander', 'Neiman Marcus', '165 Snowflake customers'],
    type: 'breach',
    impact: 'CRITICAL',
    summary: 'Info-stealer malware harvested credentials to Snowflake cloud data warehouses — 165 companies breached, 560M Ticketmaster records stolen.',
    details: 'Attackers used infostealer logs to find credentials for Snowflake accounts belonging to hundreds of companies. Snowflake had not enforced MFA. Ticketmaster (560M users), AT&T (nearly all US customers), Santander, and 163 other companies were breached. The attackers demanded ransoms. A Canadian national was arrested in cooperation with US law enforcement. AT&T paid a $370K ransom to delete stolen call records.',
    damage: '$370K ransom (AT&T); $500M+ claimed total damages',
    tags: ['infostealer', 'cloud', 'Snowflake', 'no-MFA', 'credential stuffing', 'AT&T'],
  },
  {
    id: 'xz-utils-backdoor',
    name: 'XZ Utils Supply Chain Backdoor',
    date: '2024-03',
    year: 2024,
    nation: 'Unknown',
    actors: ['Jia Tan (JiaT75)'],
    targets: ['Linux distributions', 'SSH infrastructure globally'],
    type: 'supply-chain',
    impact: 'CRITICAL',
    summary: 'A "Jia Tan" spent 2 years building trust as an open source maintainer, then inserted an SSH backdoor into XZ Utils — discovered by a Microsoft engineer by accident.',
    details: 'The attacker built a persona, "Jia Tan," over two years contributing quality code to XZ Utils while socially engineering the exhausted maintainer. The final payload, hidden in test files and activated only by a specific build toolchain, would have allowed remote code execution on millions of Linux servers via SSH. A Microsoft engineer noticed slightly elevated CPU usage in an unrelated performance test, preventing catastrophic compromise. The persona was assessed by researchers as likely a nation-state operation given the operational sophistication.',
    tags: ['supply chain', 'open source', 'SSH', 'social engineering', 'Linux', 'persona'],
  },
  {
    id: 'ivanti-zero-days-2024',
    name: 'Ivanti VPN Zero-Day Cascade',
    date: '2024-01',
    year: 2024,
    nation: 'China',
    actors: ['UTA0178', 'Volt Typhoon', 'multiple APTs'],
    targets: ['Government agencies', 'defense sector', 'Ivanti Connect Secure customers globally'],
    type: 'espionage',
    impact: 'HIGH',
    summary: 'Authentication bypass + command injection in Ivanti VPN appliances exploited by multiple nation-state actors before patches were available.',
    details: 'CVE-2024-21887 (command injection) and CVE-2023-46805 (auth bypass) were chained to achieve unauthenticated remote code execution on Ivanti Connect Secure (formerly Pulse Secure). CISA itself was forced to take offline its own IVANTI-connected systems. The Cybersecurity and Infrastructure Security Agency — the US government\'s cybersecurity authority — being compromised via the same vulnerability class it warned others about was symbolically significant. Multiple APT groups exploited simultaneously.',
    tags: ['VPN', 'auth bypass', 'command injection', 'zero-day', 'government', 'CISA'],
  },
  {
    id: 'treasury-hack-silk-typhoon',
    name: 'US Treasury / Silk Typhoon',
    date: '2024-12',
    year: 2024,
    nation: 'China',
    actors: ['Silk Typhoon', 'APT41 (linked)'],
    targets: ['US Department of the Treasury', 'OFAC', 'Office of Financial Research'],
    type: 'espionage',
    impact: 'HIGH',
    summary: 'Chinese actors breached Treasury via a compromised BeyondTrust API key, accessing the OFAC sanctions office and unclassified documents.',
    details: 'Attackers exploited a zero-day in BeyondTrust remote support software and obtained an API key to access Treasury\'s cloud environment. They accessed workstations used by OFAC — the sanctions designations office — which is particularly sensitive given China\'s desire to understand impending sanctions targeting Chinese entities. Treasury Secretary Yellen was among individuals whose unclassified email may have been accessed.',
    tags: ['Treasury', 'OFAC', 'sanctions', 'BeyondTrust', 'API key', 'zero-day'],
  },
  {
    id: 'ukraine-cyber-2022',
    name: 'Russia-Ukraine Cyber War (2022)',
    date: '2022-02',
    year: 2022,
    nation: 'Russia',
    actors: ['Sandworm', 'APT28', 'Gamaredon', 'GRU', 'Killnet'],
    targets: ['Ukraine government', 'Ukrainian banks', 'Viasat', 'media, energy, transport'],
    type: 'destructive',
    impact: 'CRITICAL',
    summary: 'Russia launched the most intensive sustained cyberwar campaign in history concurrent with the physical invasion — wiper malware, DDoS, and satellite attacks.',
    details: 'Hours before the February 24 invasion, Russia deployed AcidRain wiper against Viasat KA-SAT satellite modems, disabling Ukrainian military communications and thousands of European wind turbines. WhisperGate, HermeticWiper, IsaacWiper, CaddyWiper were deployed in waves against Ukrainian infrastructure. Microsoft\'s Digital Crimes Unit provided unprecedented real-time intelligence sharing. Despite massive Russian cyber effort, Ukraine\'s cyber resilience surprised analysts — largely attributed to pre-war cooperation with US/EU cyber agencies.',
    tags: ['wiper', 'war', 'Viasat', 'satellite', 'HermeticWiper', 'hybrid warfare'],
  },
  {
    id: 'sievert-cyber-attacks-iran-israel',
    name: 'Iran-Israel Cyber Conflict',
    date: '2021-10',
    year: 2021,
    nation: 'Iran',
    actors: ['MuddyWater', 'APT33', 'Agrius'],
    targets: ['Israeli hospitals', 'insurance companies', 'logistics firms', 'Shirbit'],
    type: 'destructive',
    impact: 'HIGH',
    summary: 'Sustained cyber operations between Iran and Israel escalated to attacks on civilian infrastructure — hospitals, water systems, and financial firms.',
    details: 'The Iran-Israel shadow cyber conflict intensified post-2020. Iran\'s Agrius group (Sand Worm-linked) deployed Fantasy and Apostle wipers against Israeli logistics and insurance firms. Israel cyber operations reportedly disrupted Iranian gas stations (October 2021) and a Shahid Rajaee port. Iranian actors later hit Israeli hospital systems and the Shirbit insurance company, leaking sensitive data. The conflict represents sustained gray-zone cyber warfare below the threshold of open conflict.',
    tags: ['wiper', 'Agrius', 'Middle East', 'hospitals', 'gray-zone', 'mutual attacks'],
  },
  {
    id: 'twitter-bitcoin-hack',
    name: 'Twitter Bitcoin Scam Hack',
    date: '2020-07',
    year: 2020,
    nation: 'Criminal',
    actors: ['Graham Ivan Clark', 'Mason John Sheppard'],
    targets: ['Twitter', 'Biden, Obama, Musk, Gates, Apple, Coinbase (accounts)'],
    type: 'financial',
    impact: 'HIGH',
    summary: 'Teenagers social engineered Twitter employees to access internal admin tools, taking over verified accounts to run a $120K Bitcoin scam.',
    details: 'Attackers called Twitter employees pretending to be IT support, convincing them to provide credentials to internal tools. They then used the admin panel to take over high-profile verified accounts — including Barack Obama, Joe Biden, Elon Musk, and Apple — to post Bitcoin scam links. $120K was collected before Twitter froze all verified accounts from tweeting for hours. The 17-year-old mastermind (Graham Clark) was sentenced to three years in a juvenile facility.',
    damage: '$120K stolen',
    tags: ['social engineering', 'vishing', 'Twitter', 'admin panel', 'teenager', 'cryptocurrency'],
  },
  {
    id: 'solarwinds-orion-hack',
    name: 'SolarWinds Orion Hack',
    date: '2020-12',
    year: 2020,
    nation: 'Russia',
    actors: ['APT29', 'SVR'],
    targets: ['FireEye', 'US CISA', 'US Treasury', 'US State Dept'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Discovered by FireEye after SVR stole their red team tools — spiraled into the discovery of the SolarWinds Orion supply chain compromise.',
    details: 'FireEye noticed unusual access patterns and reported the theft of their red team toolkit to FBI. Investigation revealed they were a victim of the SolarWinds Orion backdoor. FireEye shared 300+ countermeasures publicly and with the government. President Biden later imposed sanctions on Russia and expelled 10 diplomats. SolarWinds CEO testified to Congress. The campaign is considered the broadest and most sophisticated Russian cyber espionage campaign ever conducted against the US.',
    tags: ['SVR', 'FireEye', 'red team tools', 'espionage', 'government', 'sanctions response'],
  },
  {
    id: 'nhs-wannacry-uk',
    name: 'NHS WannaCry Impact',
    date: '2017-05',
    year: 2017,
    nation: 'North Korea',
    actors: ['Lazarus Group'],
    targets: ['National Health Service UK', '81 health trusts'],
    type: 'ransomware',
    impact: 'HIGH',
    summary: 'WannaCry paralyzed a third of UK NHS trusts — 19,000 appointments canceled including cancer treatments; ambulances diverted.',
    details: 'NHS ran Windows XP on many systems — an OS that Microsoft had stopped supporting in 2014. NHS Digital had warned trusts months earlier about the vulnerability, but many failed to patch. 80 out of 236 NHS Trusts were infected. 19,000 appointments and operations were canceled. Ambulances were diverted away from hospitals. Emergency patients were turned away. A UK government investigation found the NHS had ignored critical security warnings for years.',
    damage: '$100M NHS losses',
    tags: ['NHS', 'healthcare', 'Windows XP', 'unpatched', 'EternalBlue', 'cancelled surgeries'],
  },
  {
    id: 'icedid-emotet-takedown',
    name: 'Emotet Botnet Takedown',
    date: '2021-01',
    year: 2021,
    nation: 'Criminal',
    actors: ['TA542', 'Mealybug'],
    targets: ['Emotet infrastructure (8 countries)'],
    type: 'destructive',
    impact: 'HIGH',
    summary: 'Europol-led operation seized Emotet\'s infrastructure across Europe, deploying a self-destruct update to infected machines worldwide.',
    details: 'Emotet was the world\'s most dangerous malware botnet — a spam/dropper service that delivered TrickBot, QBot, and ransomware to millions of machines. Operation LADYBIRD involved authorities from the Netherlands, Germany, US, UK, France, Lithuania, Canada, and Ukraine. They seized 700+ C2 servers and deployed a benign "Emotet.dll" update to all infected systems that uninstalled the malware on April 25, 2021. Emotet later resurfaced in November 2021.',
    tags: ['botnet', 'Europol', 'law enforcement', 'takedown', 'dropper', 'TrickBot'],
  },
  {
    id: 'medibank-optus-australia',
    name: 'Medibank Breach (Australia)',
    date: '2022-10',
    year: 2022,
    nation: 'Criminal',
    actors: ['REvil-linked', 'Russian cybercriminals'],
    targets: ['Medibank Private', '9.7M Australians'],
    type: 'breach',
    impact: 'HIGH',
    summary: 'Stolen credentials exposed sensitive health data for 9.7M Australians including HIV diagnoses, mental health records, and drug treatment data.',
    details: 'Attackers obtained credentials from an IT contractor\'s machine. Medibank refused to pay ransom. Attackers released health claim data including mental health, drug abuse, and HIV treatment records on the dark web in batches. The breach drove Australia to significantly increase its cyber investment and cooperation with Five Eyes partners. Australian Federal Police later attributed the attack to Russian nationals. Following Optus (11M records) and Medibank breaches, Australia raised maximum fines for data breaches to $50M AUD.',
    tags: ['healthcare', 'credential theft', 'extortion', 'Australia', 'sensitive health data'],
  },
  {
    id: 'lazarus-crypto-heists',
    name: 'Lazarus Crypto Heists (Cumulative)',
    date: '2022-03',
    year: 2022,
    nation: 'North Korea',
    actors: ['Lazarus Group', 'AppleJeus', 'BlueNorOff'],
    targets: ['Ronin Network ($625M)', 'Harmony Horizon ($100M)', 'Bybit ($1.5B)'],
    type: 'financial',
    impact: 'CRITICAL',
    summary: 'North Korea stole $3B+ in cryptocurrency 2016-2024 to fund its weapons programs — UN estimates crypto theft funds 40% of NK missile program.',
    details: 'The Lazarus Group pivoted heavily to cryptocurrency theft after 2018, developing specialized capabilities including trojanized crypto wallets and fake job applications. The Ronin Network hack ($625M) in March 2022 — the largest single crypto theft — was conducted by compromising 5 of 9 validator nodes. UN Panel of Experts assessed North Korea stole $3B in crypto 2017-2023. The February 2025 Bybit hack ($1.5B) by Lazarus was the largest single crypto heist in history.',
    damage: '$3B+ cumulative; $1.5B Bybit alone',
    tags: ['cryptocurrency', 'DeFi', 'Lazarus', 'Ronin', 'Bybit', 'UN sanctions evasion'],
  },
  {
    id: 'apache-log4j-2',
    name: 'Marriott Breach',
    date: '2018-09',
    year: 2018,
    nation: 'China',
    actors: ['APT40', 'Hainan State Security'],
    targets: ['Marriott International / Starwood', '500M guests'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Chinese intelligence accessed Starwood\'s reservation system for 4 years after the Marriott acquisition, collecting travel data on 500M guests.',
    details: 'The breach began in 2014 in Starwood\'s network, two years before Marriott acquired Starwood. Despite standard acquisition due diligence, the backdoor was not found. Marriott inherited it. Exposed data included passport numbers, travel dates, arrival/departure, and payment card information — a counterintelligence goldmine for tracking government and military personnel travel patterns. UK\'s ICO fined Marriott £18.4M. The US formally attributed the hack to China\'s Ministry of State Security in 2020.',
    damage: '$126M+ in fines and remediation',
    tags: ['espionage', 'hotel', 'travel data', 'MSS', 'M&A', 'passport numbers'],
  },
  {
    id: 'apache-struts-equifax',
    name: 'Anthem Health Breach',
    date: '2015-01',
    year: 2015,
    nation: 'China',
    actors: ['Deep Panda', 'APT19'],
    targets: ['Anthem Inc.', '78.8M Americans'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'Nation-state actors stole 78.8M healthcare records — the largest healthcare breach in US history until Change Healthcare (2024).',
    details: 'Attackers gained access via a spearphishing email to a system administrator. Anthem stored all data unencrypted — industry standard "encrypt at rest" practices were not followed. Stolen records contained SSNs, employment data, income data, names, addresses, and birthdays. DOJ later indicted a Chinese national linked to the breach. The data was assessed as primarily valuable for counterintelligence purposes — identifying intelligence community employees enrolled in Anthem plans rather than financial fraud.',
    damage: '$115M settlement; largest healthcare settlement ever',
    tags: ['healthcare', 'espionage', 'PII', 'unencrypted data', 'counterintelligence'],
  },
  {
    id: 'cloudhopper-apt10',
    name: 'Operation Cloud Hopper (APT10)',
    date: '2016-01',
    year: 2016,
    nation: 'China',
    actors: ['APT10', 'Stone Panda', 'menuPass'],
    targets: ['Managed Service Providers globally', '45+ companies in 12 countries'],
    type: 'espionage',
    impact: 'CRITICAL',
    summary: 'APT10 systematically compromised MSPs to pivot into their clients\' networks — achieving multi-sector espionage via a single entry point.',
    details: 'Cloud Hopper targeted MSPs as a force multiplier — compromising one provider gave access to dozens of clients. APT10 stole hundreds of gigabytes of intellectual property from aviation, satellite, pharma, oil & gas, and government clients. The US, UK, Australia, Canada, Japan, and EU jointly attributed the operation to China\'s Ministry of State Security (Tianjin Bureau). The operation persisted for at least three years before being publicly exposed.',
    tags: ['MSP', 'supply chain', 'APT10', 'IP theft', 'multi-sector', 'Five Eyes attribution'],
  },
  {
    id: 'solarwinds-hafnium-combo',
    name: 'HAFNIUM ProxyShell (2021)',
    date: '2021-08',
    year: 2021,
    nation: 'Multiple',
    actors: ['LockFile', 'Conti', 'Squirrelwaffle', 'BlackByte'],
    targets: ['Exchange Servers globally'],
    type: 'ransomware',
    impact: 'HIGH',
    summary: 'A second wave of Exchange vulnerabilities (ProxyShell) enabled ransomware groups to exploit the same server class within weeks of disclosure.',
    details: 'ProxyShell (CVE-2021-34473, 34523, 31207) built on ProxyLogon\'s architecture. Security researcher Orange Tsai demonstrated the chain at Black Hat 2021. Within days, ransomware operators began mass scanning and exploitation. LockFile ransomware appeared specifically targeting Exchange servers. The rapid ransomware follow-on to vulnerability disclosures became a recognized pattern that defenders needed to prioritize patch timelines around.',
    tags: ['Exchange', 'ProxyShell', 'ransomware', 'mass exploitation', 'patch timing'],
  },
  {
    id: 'cyberattack-ukraine-power-2016',
    name: 'Industroyer / Crash Override',
    date: '2016-12',
    year: 2016,
    nation: 'Russia',
    actors: ['Sandworm'],
    targets: ['Ukraine Ukrenergo power grid', 'Kiev transmission'],
    type: 'destructive',
    impact: 'HIGH',
    summary: 'Second Ukraine power grid attack using Industroyer — purpose-built ICS malware capable of speaking native grid protocols.',
    details: 'Industroyer (also known as Crash Override) was the first malware since Stuxnet designed to directly attack power grids. Unlike Stuxnet targeting PLCs, Industroyer spoke native ICS protocols (IEC 101, IEC 104, IEC 61850, OPC DA) allowing direct interaction with substation equipment. A fifth component targeted safety systems. The attack caused a 1-hour blackout in northern Kiev affecting ~200,000 people. ESET and Dragos jointly discovered and analyzed the malware.',
    tags: ['ICS', 'Industroyer', 'power grid', 'IEC 104', 'native protocol', 'Kiev'],
  },
  {
    id: 'yahoo-breach',
    name: 'Yahoo! Mega Breach',
    date: '2013-08',
    year: 2013,
    nation: 'Criminal / Russia',
    actors: ['Alexsey Belan', 'FSB Officers Dokuchaev & Sushchin'],
    targets: ['Yahoo! Inc.', '3 billion accounts'],
    type: 'breach',
    impact: 'CRITICAL',
    summary: 'Two FSB officers directed criminal hackers to breach Yahoo — accessing 3 billion accounts, the largest data breach in history.',
    details: 'The breach occurred in 2013-2014 but was not disclosed until 2016-17. Initially reported as 500M accounts, it was revised to encompass all 3 billion Yahoo accounts. DOJ indicted two FSB officers (Baratov and Belan) in 2017 — the first US indictment of Russian government intelligence officers for hacking. FSB used criminal hackers as contractors. The breach impacted Verizon\'s $4.8B acquisition of Yahoo, reducing the price by $350M.',
    damage: '$350M Verizon acquisition price reduction',
    tags: ['FSB', 'state-criminal nexus', 'data breach', 'largest ever', 'account takeover'],
  },
  {
    id: 'cozy-bear-covid-vaccine',
    name: 'APT29 COVID Vaccine Espionage',
    date: '2020-07',
    year: 2020,
    nation: 'Russia',
    actors: ['APT29 (Cozy Bear)', 'SVR'],
    targets: ['AstraZeneca', 'Oxford University', 'Canadian NRCC', 'UK NCSC agencies'],
    type: 'espionage',
    impact: 'HIGH',
    summary: 'SVR targeted COVID-19 vaccine researchers in the UK, Canada, and US to steal vaccine data during the global race.',
    details: 'The UK NCSC, Canadian CSE, and US NSA/CISA issued a joint advisory attributing attacks on vaccine development organizations to APT29. Tactics included spearphishing, custom malware (WellMess, WellMail), and exploitation of Citrix, Pulse Secure, Fortinet VPN vulnerabilities. The Russian government denied involvement. The theft was assessed as seeking to obtain vaccine data before Russia\'s own Sputnik V development succeeded.',
    tags: ['COVID-19', 'vaccine', 'espionage', 'SVR', 'biotech', 'joint advisory'],
  },
  {
    id: 'dearcry-msexchange',
    name: 'DPRK Crypto Mixer Sanction',
    date: '2022-08',
    year: 2022,
    nation: 'North Korea',
    actors: ['Lazarus Group', 'Blender.io', 'Tornado Cash'],
    targets: ['Tornado Cash ($7B laundered)', 'Blender.io'],
    type: 'financial',
    impact: 'HIGH',
    summary: 'OFAC sanctioned Tornado Cash cryptocurrency mixer used by Lazarus Group to launder $455M — first sanction of decentralized code.',
    details: 'OFAC designated Tornado Cash and its associated addresses, alleging it was used by Lazarus Group to launder $455M from the Ronin hack and hundreds of millions more. The sanction of an open-source smart contract protocol (rather than a company) was legally controversial. Two Tornado Cash developers were arrested in the Netherlands and US. The action signaled US intent to pursue crypto laundering infrastructure regardless of its decentralized nature.',
    tags: ['cryptocurrency', 'money laundering', 'Tornado Cash', 'sanctions', 'decentralized', 'OFAC'],
  },
  {
    id: 'oldsmar-water-hack',
    name: 'Oldsmar Water Treatment Attack',
    date: '2021-02',
    year: 2021,
    nation: 'Unknown',
    actors: ['Unknown'],
    targets: ['Oldsmar Florida Water Treatment Plant'],
    type: 'destructive',
    impact: 'HIGH',
    summary: 'Hacker remotely accessed Florida water plant controls and raised sodium hydroxide to 111x the safe level — caught by an alert operator.',
    details: 'An attacker accessed the Oldsmar water treatment plant\'s HMI via remote desktop software (TeamViewer). The attacker moved the sodium hydroxide (lye) dosing setpoint from 111 parts per million to 11,100 ppm — a potentially lethal level. An operator watching the screen noticed the cursor moving and reversed the change within seconds. Investigation found the plant used a 32-bit Windows 7 workstation (EOL since 2020), had shared TeamViewer credentials, and no firewall between IT and OT networks.',
    tags: ['water', 'OT', 'critical infrastructure', 'TeamViewer', 'remote access', 'near-miss'],
  },
  {
    id: 'ransomware-hospital-deaths',
    name: 'Düsseldorf Hospital Ransomware',
    date: '2020-09',
    year: 2020,
    nation: 'Criminal',
    actors: ['Suspected DoppelPaymer'],
    targets: ['University Hospital Düsseldorf', 'patient in emergency'],
    type: 'ransomware',
    impact: 'HIGH',
    summary: 'First potential ransomware-linked patient death — hospital systems down forced ambulance diversion; patient died during rerouting.',
    details: 'DoppelPaymer ransomware (later determined to be targeted at Düsseldorf University rather than the hospital) encrypted 30 servers. The hospital was unable to admit emergency cases. A patient requiring urgent care was rerouted to a hospital 30km away and died. German prosecutors opened a negligent homicide investigation — believed to be the first ransomware-related homicide investigation. The attackers provided decryption key without ransom when informed a hospital was hit.',
    tags: ['healthcare', 'patient death', 'ransomware', 'hospital diversion', 'Germany', 'negligent homicide'],
  },
  {
    id: 'apts-on-ukraine',
    name: 'Ghostwriter / Influence Ops Ukraine',
    date: '2020-03',
    year: 2020,
    nation: 'Russia / Belarus',
    actors: ['GRU', 'UNC1151 (Ghostwriter)', 'Belarus State Security'],
    targets: ['European public opinion', 'Ukraine, Poland, Lithuania, Latvia governments'],
    type: 'influence',
    impact: 'HIGH',
    summary: 'Multi-year Russian/Belarusian influence operation fabricated quotes from European officials and hacked government websites to spread disinformation.',
    details: 'Ghostwriter compromised government and media websites to publish fabricated articles attributed to real officials, including fake quotes from NATO military commanders about withdrawing troops. The operation predated the 2022 invasion and focused on undermining support for NATO and EU in Eastern Europe. Mandiant attributed the operation to Belarus\'s GRU-linked cyber actors. Operations intensified significantly in the weeks before the February 2022 invasion.',
    tags: ['influence operation', 'disinformation', 'NATO', 'GRU', 'website defacement', 'fabrication'],
  },
  {
    id: 'midnight-blizzard-teams',
    name: 'Midnight Blizzard / Teams Phishing',
    date: '2023-08',
    year: 2023,
    nation: 'Russia',
    actors: ['APT29 (Midnight Blizzard)'],
    targets: ['~40 organizations', 'government agencies', 'NGOs', 'IT companies'],
    type: 'espionage',
    impact: 'HIGH',
    summary: 'SVR created Microsoft Teams accounts mimicking IT support to conduct social engineering phishing against government targets.',
    details: 'Midnight Blizzard created Microsoft 365 tenants with IT support-themed display names (e.g., "Microsoft Identity Protection") and initiated Teams chats with targets, convincing them to approve MFA prompts. The technique exploited legitimate cross-tenant communication features in Teams. Approximately 40 organizations globally were targeted, including government agencies in the US and EU. Microsoft later imposed restrictions on external Teams communication in response.',
    tags: ['Teams', 'social engineering', 'MFA phishing', 'cross-tenant', 'SVR', 'government'],
  },
  {
    id: 'china-microsoft-email-storm',
    name: 'Storm-0558 / State Dept Email',
    date: '2023-07',
    year: 2023,
    nation: 'China',
    actors: ['Storm-0558'],
    targets: ['US State Department', 'US Commerce Secretary', '25 organizations'],
    type: 'espionage',
    impact: 'HIGH',
    summary: 'Chinese actors forged Microsoft authentication tokens to access State Department email — including Commerce Secretary Raimondo\'s account.',
    details: 'Storm-0558 acquired a Microsoft account signing key through an unknown method and used it to forge authentication tokens for Microsoft\'s cloud email service. This gave access to ~25 organizations including the US State Department. Commerce Secretary Gina Raimondo\'s email — she oversees export controls on Chinese tech — was specifically accessed. The breach was discovered by State Department security teams who noticed unusual access patterns. The cryptographic signing key should have been isolated and protected — how it was obtained remains a Microsoft security failure under investigation.',
    tags: ['email', 'forged tokens', 'State Department', 'signing key', 'cloud', 'Commerce Secretary'],
  },
  {
    id: 'bybit-lazarus-2025',
    name: 'Bybit Exchange Hack — $1.5B',
    date: '2025-02',
    year: 2025,
    nation: 'North Korea',
    actors: ['Lazarus Group', 'TraderTraitor'],
    targets: ['Bybit cryptocurrency exchange'],
    type: 'financial',
    impact: 'CRITICAL',
    summary: 'Lazarus Group stole $1.5B from Bybit in the largest single cryptocurrency heist in history — compromising a Safe multisig cold wallet.',
    details: 'Lazarus compromised a Safe{Wallet} developer\'s machine to inject malicious JavaScript into the Safe front-end served specifically to Bybit. When Bybit executed a routine transfer, the malicious UI showed the correct destination while the underlying transaction was manipulated to transfer $1.5B to attacker-controlled addresses. Bybit CEO Ben Zhou livestreamed the incident response. Lazarus laundered funds through THORChain. The US, UK, and Australia issued advisories. Total Lazarus crypto theft exceeds $6B lifetime.',
    damage: '$1.5B stolen',
    tags: ['cryptocurrency', 'Bybit', 'Safe multisig', 'supply chain', 'UI manipulation', 'TraderTraitor'],
  },
  {
    id: 'trump-staffers-signal-chat',
    name: 'Signal Chat Leak — Houthi Strike Plans',
    date: '2025-03',
    year: 2025,
    nation: 'USA (internal)',
    actors: ['Trump cabinet officials'],
    targets: ['US classified operations security'],
    type: 'espionage',
    impact: 'HIGH',
    summary: 'National Security Advisor Waltz accidentally added The Atlantic editor to a Signal chat discussing imminent Houthi strike plans — a major OPSEC failure.',
    details: 'NSA Mike Waltz accidentally added The Atlantic\'s editor-in-chief Jeffrey Goldberg to a group chat labeled "Houthi PC small group" on Signal. The chat included SecDef Pete Hegseth sharing attack sequencing, weapons systems, and timing for US strikes in Yemen. Goldberg published the chat. The incident raised serious questions about government officials discussing classified operations on commercial messaging apps rather than secured government systems. Several cabinet members claimed the information was not classified.',
    tags: ['OPSEC', 'Signal', 'classified', 'Yemen', 'Houthi', 'accidental disclosure'],
  },
  {
    id: 'oracle-cloud-breach-2025',
    name: 'Oracle Cloud Data Breach',
    date: '2025-03',
    year: 2025,
    nation: 'Criminal',
    actors: ['rose87168'],
    targets: ['Oracle Cloud Infrastructure', '6M records from 140,000+ tenants'],
    type: 'breach',
    impact: 'HIGH',
    summary: 'Threat actor claimed to breach Oracle Cloud SSO and LDAP, posting samples of 6M user records for sale — Oracle initially denied, then quietly confirmed.',
    details: 'A threat actor using the alias "rose87168" posted Oracle Cloud authentication data, LDAP entries, and customer SSO credentials on dark web forums, offering to sell data from 140,000+ tenants. Oracle initially denied any breach. Researchers and affected companies confirmed data authenticity. The attacker exploited a vulnerable Oracle login endpoint (login.us2.oraclecloud.com running Oracle Access Manager 11.1.2.3.230). Oracle later acknowledged a breach of a "legacy environment" without confirming details publicly.',
    tags: ['Oracle', 'cloud', 'SSO', 'LDAP', 'denial', 'legacy system'],
  },
  {
    id: 'doge-data-access',
    name: 'DOGE Federal Data Access Controversy',
    date: '2025-02',
    year: 2025,
    nation: 'USA (internal)',
    actors: ['DOGE (Dept of Government Efficiency)', 'Elon Musk affiliates'],
    targets: ['Treasury BFS', 'SSA', 'IRS', 'USAID', 'HHS', 'federal employee data'],
    type: 'espionage',
    impact: 'HIGH',
    summary: 'DOGE operatives obtained broad access to federal payment systems, Social Security databases, and IRS records — sparking federal lawsuits and court injunctions.',
    details: 'Young DOGE engineers obtained root access to Treasury\'s Bureau of the Fiscal Service (controlling federal payments), SSA systems (60M beneficiary records), IRS databases (tax records for all Americans), and USAID systems. At least one DOGE staffer had a prior cybersecurity conviction. Federal judges issued temporary restraining orders. Multiple Inspector General offices opened investigations. Privacy advocates argued the access violated the Privacy Act. Career government security officials described the access as unprecedented and creating serious counterintelligence risks.',
    tags: ['government', 'insider threat', 'Treasury', 'SSA', 'IRS', 'privacy', 'court injunctions'],
  },
];

export const INCIDENT_TYPES: { value: IncidentType; label: string; color: string }[] = [
  { value: 'espionage',     label: 'Espionage',     color: '#1e9eff' },
  { value: 'destructive',  label: 'Destructive',   color: '#ff3a3a' },
  { value: 'ransomware',   label: 'Ransomware',    color: '#ff8800' },
  { value: 'financial',    label: 'Financial',     color: '#ffaa00' },
  { value: 'influence',    label: 'Influence',     color: '#b464ff' },
  { value: 'supply-chain', label: 'Supply Chain',  color: '#00c9b0' },
  { value: 'breach',       label: 'Data Breach',   color: '#ff6b9d' },
];

export const IMPACT_COLORS: Record<ImpactLevel, string> = {
  CRITICAL: '#ff3a3a',
  HIGH: '#ff8800',
  MEDIUM: '#ffaa00',
};

export const NATION_COLORS: Record<string, string> = {
  'Russia': '#ff3a3a',
  'China': '#ff8800',
  'North Korea': '#ffaa00',
  'Iran': '#b464ff',
  'USA / Israel': '#1e9eff',
  'USA (internal)': '#7a9bb5',
  'Criminal': '#ff6b9d',
  'Multiple': '#00c9b0',
  'Unknown': '#5a7a94',
};
